# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Programming\GitHub\Reynaldo_Junior-6\TechCheck\TC7\MainWindowTC7.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 443)
        font = QtGui.QFont()
        font.setPointSize(6)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(220, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButtonCalculate.setFont(font)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.labelDependentnum = QtWidgets.QLabel(self.centralwidget)
        self.labelDependentnum.setGeometry(QtCore.QRect(201, 298, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDependentnum.setFont(font)
        self.labelDependentnum.setText("")
        self.labelDependentnum.setObjectName("labelDependentnum")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(216, 294, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 350, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEditWeeklySalary = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWeeklySalary.setGeometry(QtCore.QRect(288, 54, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditWeeklySalary.setFont(font)
        self.lineEditWeeklySalary.setObjectName("lineEditWeeklySalary")
        self.lineEditDependentnum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDependentnum.setGeometry(QtCore.QRect(370, 120, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDependentnum.setFont(font)
        self.lineEditDependentnum.setObjectName("lineEditDependentnum")
        self.labelProvincialTax = QtWidgets.QLabel(self.centralwidget)
        self.labelProvincialTax.setGeometry(QtCore.QRect(190, 240, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelProvincialTax.setFont(font)
        self.labelProvincialTax.setText("")
        self.labelProvincialTax.setObjectName("labelProvincialTax")
        self.labelFederalTax = QtWidgets.QLabel(self.centralwidget)
        self.labelFederalTax.setGeometry(QtCore.QRect(179, 269, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelFederalTax.setFont(font)
        self.labelFederalTax.setText("")
        self.labelFederalTax.setObjectName("labelFederalTax")
        self.labelDependentDeduction = QtWidgets.QLabel(self.centralwidget)
        self.labelDependentDeduction.setGeometry(QtCore.QRect(307, 298, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDependentDeduction.setFont(font)
        self.labelDependentDeduction.setText("")
        self.labelDependentDeduction.setObjectName("labelDependentDeduction")
        self.labelTotalWtihheld = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalWtihheld.setGeometry(QtCore.QRect(135, 329, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTotalWtihheld.setFont(font)
        self.labelTotalWtihheld.setText("")
        self.labelTotalWtihheld.setObjectName("labelTotalWtihheld")
        self.labelTotalTakeHome = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalTakeHome.setGeometry(QtCore.QRect(186, 358, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTotalTakeHome.setFont(font)
        self.labelTotalTakeHome.setText("")
        self.labelTotalTakeHome.setObjectName("labelTotalTakeHome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tax Calculator"))
        self.label.setText(_translate("MainWindow", "What is your weekly salary?"))
        self.label_2.setText(_translate("MainWindow", "How many dependents do you have? "))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate Tax"))
        self.label_3.setText(_translate("MainWindow", "Provincial Tax Withheld: "))
        self.label_4.setText(_translate("MainWindow", "Federal Tax Withheld:"))
        self.label_5.setText(_translate("MainWindow", "Dependent Deduction for "))
        self.label_7.setText(_translate("MainWindow", "dependents:"))
        self.label_8.setText(_translate("MainWindow", "Total Withheld:"))
        self.label_9.setText(_translate("MainWindow", "Total Take-Home Pay:"))
