# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Programming\Assign_5\MainWindowCountries.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 706)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelListTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelListTitle.setGeometry(QtCore.QRect(10, 20, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelListTitle.setFont(font)
        self.labelListTitle.setObjectName("labelListTitle")
        self.labelCountryName = QtWidgets.QLabel(self.centralwidget)
        self.labelCountryName.setGeometry(QtCore.QRect(340, 80, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelCountryName.setFont(font)
        self.labelCountryName.setText("")
        self.labelCountryName.setObjectName("labelCountryName")
        self.labelFlagImage = QtWidgets.QLabel(self.centralwidget)
        self.labelFlagImage.setGeometry(QtCore.QRect(370, 150, 251, 151))
        self.labelFlagImage.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.labelFlagImage.setText("")
        self.labelFlagImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFlagImage.setObjectName("labelFlagImage")
        self.linePopulationInfo = QtWidgets.QLineEdit(self.centralwidget)
        self.linePopulationInfo.setGeometry(QtCore.QRect(420, 330, 231, 21))
        self.linePopulationInfo.setInputMask("")
        self.linePopulationInfo.setText("")
        self.linePopulationInfo.setFrame(True)
        self.linePopulationInfo.setObjectName("linePopulationInfo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(337, 313, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonUpdatePopulation = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUpdatePopulation.setGeometry(QtCore.QRect(530, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonUpdatePopulation.setFont(font)
        self.buttonUpdatePopulation.setObjectName("buttonUpdatePopulation")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(341, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBoxAreaConversion = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxAreaConversion.setGeometry(QtCore.QRect(441, 426, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBoxAreaConversion.setFont(font)
        self.comboBoxAreaConversion.setObjectName("comboBoxAreaConversion")
        self.comboBoxAreaConversion.addItem("")
        self.comboBoxAreaConversion.addItem("")
        self.labelAreaValue = QtWidgets.QLabel(self.centralwidget)
        self.labelAreaValue.setGeometry(QtCore.QRect(530, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelAreaValue.setFont(font)
        self.labelAreaValue.setObjectName("labelAreaValue")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(330, 500, 321, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioSqMile = QtWidgets.QRadioButton(self.groupBox)
        self.radioSqMile.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.radioSqMile.setChecked(True)
        self.radioSqMile.setObjectName("radioSqMile")
        self.radioSqKm = QtWidgets.QRadioButton(self.groupBox)
        self.radioSqKm.setGeometry(QtCore.QRect(20, 50, 131, 41))
        self.radioSqKm.setObjectName("radioSqKm")
        self.labelDensityValue = QtWidgets.QLabel(self.groupBox)
        self.labelDensityValue.setGeometry(QtCore.QRect(198, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelDensityValue.setFont(font)
        self.labelDensityValue.setObjectName("labelDensityValue")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 605, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.labelWorldPop = QtWidgets.QLabel(self.centralwidget)
        self.labelWorldPop.setGeometry(QtCore.QRect(550, 615, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelWorldPop.setFont(font)
        self.labelWorldPop.setObjectName("labelWorldPop")
        self.listCountries = QtWidgets.QListWidget(self.centralwidget)
        self.listCountries.setGeometry(QtCore.QRect(10, 70, 291, 591))
        self.listCountries.setObjectName("listCountries")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoadCountries = QtWidgets.QAction(MainWindow)
        self.actionLoadCountries.setObjectName("actionLoadCountries")
        self.actionSavetoFile = QtWidgets.QAction(MainWindow)
        self.actionSavetoFile.setEnabled(False)
        self.actionSavetoFile.setObjectName("actionSavetoFile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoadCountries)
        self.menuFile.addAction(self.actionSavetoFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Countries of the World"))
        self.labelListTitle.setText(_translate("MainWindow", "Choose a country from the list:"))
        self.label.setText(_translate("MainWindow", "Population:"))
        self.buttonUpdatePopulation.setText(_translate("MainWindow", "Update Population "))
        self.label_2.setText(_translate("MainWindow", "Total area in"))
        self.comboBoxAreaConversion.setItemText(0, _translate("MainWindow", "Sq. Miles"))
        self.comboBoxAreaConversion.setItemText(1, _translate("MainWindow", "Sq. Km"))
        self.labelAreaValue.setText(_translate("MainWindow", "Area_Value"))
        self.groupBox.setTitle(_translate("MainWindow", "Population Density"))
        self.radioSqMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioSqKm.setText(_translate("MainWindow", "Per Square Km"))
        self.labelDensityValue.setText(_translate("MainWindow", "Density_Value"))
        self.label_4.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.labelWorldPop.setText(_translate("MainWindow", "World_pop."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoadCountries.setText(_translate("MainWindow", "Load Countries"))
        self.actionSavetoFile.setText(_translate("MainWindow", "Save to File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
